import { readFileSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";

// Dresses the seeded demo in German, so the German brochure shows a German job.
//
// A German EPC opening a brochure full of "Podkonstrukcija" and "Cesta Staneta
// Žagarja 69, 4000 Kranj" reads it as somebody else's product in somebody
// else's country, and stops reading. Every string that reaches a screenshot or
// a generated document has to be German BEFORE the pipeline runs, because the
// documents render from the database, not from the UI.
//
// This is an OVERLAY, not a seed variant. It runs after `npm run seed`, rewrites
// the demo rows in place, and `npm run seed` puts everything back, so the
// founder's Slovenian demo is never at risk. That also makes the restore
// trivially verifiable: it is the same command he already runs before a demo.
//
// It also replaces the EPC's name. The Slovenian demo names a real ZSFV member
// company, which is fine inside a private demo and not fine on a brochure sent
// to that company's competitors. The German edition uses an invented firm.

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) {
  console.error("Missing Supabase env vars. Run via: npm run marketing:de");
  process.exit(1);
}
const db = createClient(url, key, { auth: { persistSession: false } });

const EPC_ORG = "11111111-1111-4111-8111-111111111111";
const SUB_ORG_2 = "22222222-2222-4222-8222-222222222223";
const SUB_ORG_3 = "22222222-2222-4222-8222-222222222224";
const PROJECT = "33333333-3333-4333-8333-333333333333";
const PROJECT_START = "33333333-3333-4333-8333-333333333334";
const PERSON_EPC = "66666666-6666-4666-8666-666666666601";
const PERSON_EPC_ADMIN = "66666666-6666-4666-8666-666666666605";

/**
 * Every free-text string the demo carries, mapped.
 *
 * Applied by EXACT MATCH across the content columns below. Anything not in
 * this table stays Slovenian, which is deliberate: it then shows up in the
 * screenshots and gets noticed, instead of being silently half-translated.
 */
const TEXT = {
  // scope items
  "Podkonstrukcija": "Unterkonstruktion",
  "Moduli": "Module",
  "DC kabliranje": "DC-Verkabelung",
  // daily notes
  "Začetek montaže podkonstrukcije, južni del strehe.":
    "Beginn Montage Unterkonstruktion, Südseite des Daches.",
  "Podkonstrukcija, nadaljevanje proti sredini.":
    "Unterkonstruktion, weiter Richtung Dachmitte.",
  "Podkonstrukcija, zahodni niz.": "Unterkonstruktion, westliche Reihe.",
  "Podkonstrukcija zaključena.": "Unterkonstruktion abgeschlossen.",
  "Začetek montaže modulov, prvi niz.": "Beginn Modulmontage, erste Reihe.",
  "Moduli, drugi niz.": "Module, zweite Reihe.",
  "Moduli in začetek DC kabliranja.": "Module und Beginn der DC-Verkabelung.",
  "Popoldne prekinitev zaradi dežja.": "Nachmittags Unterbrechung wegen Regen.",
  "Moduli in DC, dober tempo.": "Module und DC, gutes Tempo.",
  // material list
  "Modul Trina Vertex S+ 450 W": "Modul Trina Vertex S+ 450 W",
  "Nosilna konstrukcija K2 Dome 6.10": "Unterkonstruktion K2 Dome 6.10",
  "Razsmernik Huawei SUN2000-100KTL": "Wechselrichter Huawei SUN2000-100KTL",
  "DC kabel 6 mm2": "DC-Kabel 6 mm2",
  "Konektorji MC4": "MC4-Steckverbinder",
  "AC kabel 4x120 mm2": "AC-Kabel 4x120 mm2",
  "Prenapetostna zaščita tip 2": "Überspannungsschutz Typ 2",
  // hours, change orders, money
  "Dodatno pritrjevanje zaradi drugačne kritine":
    "Zusätzliche Befestigung wegen abweichender Dacheindeckung",
  "Nadaljevanje pritrjevanja, južni del": "Fortsetzung der Befestigung, Südseite",
  "Čiščenje po neurju": "Reinigung nach Unwetter",
  "Zamenjava dotrajanih letev pod kritino":
    "Austausch schadhafter Dachlatten unter der Eindeckung",
  "Montaža FV sistema 245.7 kWp, Kranj": "Montage PV-Anlage 245,7 kWp, Ingolstadt",
  // incidents and requests
  "Dostop do strehe zaprt zaradi dostave drugega izvajalca.":
    "Dachzugang gesperrt wegen Anlieferung eines anderen Gewerks.",
  "Zmanjkalo je 12 vijakov M10 za zaključne vrste.":
    "Es fehlen 12 Schrauben M10 für die Abschlussreihen.",
  "Vijaki gredo jutri zjutraj s prvo dostavo.":
    "Die Schrauben kommen morgen früh mit der ersten Lieferung.",
  "Potrebujemo shemo priklopa za razdelilnik R2.":
    "Wir benötigen den Anschlussplan für den Verteiler R2.",
  "Vse prevzeto, dobavnica priložena.": "Alles übernommen, Lieferschein beigefügt.",
  // units
  kos: "Stk",
  kpl: "Stk",
  par: "Paar",
};

/** Tables and the free-text columns in them that the mapping applies to. */
const CONTENT = [
  ["scope_items", ["name", "unit"]],
  ["daily_entries", ["note"]],
  ["material_items", ["name", "unit"]],
  ["hour_sheet_lines", ["description"]],
  ["change_orders", ["title"]],
  ["purchase_order_lines", ["description"]],
  // invoices carry their lines as JSON and are REGENERATED by the demo flow
  // after this runs, so they inherit German from the order and the hour sheets
  // rather than needing a rewrite here.
  ["incidents", ["note"]],
  ["requests", ["text", "response_note"]],
  ["material_checks", ["note"]],
];

/**
 * Rewrites every mapped value in one table.
 *
 * Reads the column once and updates only the rows that actually change, rather
 * than firing an update per mapping per column, which was both four hundred
 * round trips and a malformed request: chaining a head select onto an update
 * fails rather than counting it.
 */
async function translateTable(table, columns) {
  const { data, error } = await db.from(table).select(["id", ...columns].join(", "));
  if (error) {
    if (/does not exist|column|relation/i.test(error.message)) return 0;
    throw new Error(`${table}: ${error.message}`);
  }

  let changed = 0;
  for (const row of data ?? []) {
    const patch = {};
    for (const column of columns) {
      const value = row[column];
      if (typeof value === "string" && TEXT[value] !== undefined && TEXT[value] !== value) {
        patch[column] = TEXT[value];
      }
    }
    if (Object.keys(patch).length === 0) continue;
    const { error: updateError } = await db.from(table).update(patch).eq("id", row.id);
    if (updateError) throw new Error(`${table}.${row.id}: ${updateError.message}`);
    changed += Object.keys(patch).length;
  }
  return changed;
}

async function main() {
  console.log("dressing the demo in German ...");

  // 1. The companies. The EPC gets an invented German name; AVESOL stays,
  //    because a Slovenian montage subcontractor on a German site is exactly
  //    the founder's real business and reads as true.
  await db.from("organizations").update({ name: "Nordsonne Energie GmbH", country: "de" }).eq("id", EPC_ORG);
  await db.from("organizations").update({ name: "Kos Montagebau GmbH", country: "de" }).eq("id", SUB_ORG_2);
  await db.from("organizations").update({ name: "Elektro Vrhnika GmbH", country: "de" }).eq("id", SUB_ORG_3);

  // 2. The EPC's people. The subcontractor's crew keeps Slovenian names.
  await db.from("people").update({ full_name: "Matthias Kern" }).eq("id", PERSON_EPC);
  await db.from("people").update({ full_name: "Michael Berger" }).eq("id", PERSON_EPC_ADMIN);

  // 3. The projects. `language` is what makes the generated PDFs German; the
  //    address is what stops a German reader treating it as somebody else's job.
  await db
    .from("projects")
    .update({
      name: "PV-Anlage Logistikzentrum Ingolstadt",
      address_street: "Marie-Curie-Straße 14",
      address_zip: "85055",
      address_city: "Ingolstadt",
      country: "de",
      language: "de",
    })
    .eq("id", PROJECT);

  await db
    .from("projects")
    .update({
      name: "Gewerbepark München Ost",
      address_street: "Gruber Straße 22",
      address_zip: "85586",
      address_city: "Poing",
      country: "de",
      language: "de",
    })
    .eq("id", PROJECT_START);

  // 4. The rest of the book, so the portfolio screenshot is not half Slovenian.
  const { data: book } = await db
    .from("projects")
    .select("id, name")
    .not("id", "in", `(${PROJECT},${PROJECT_START})`);
  const BOOK = {
    "Poslovna cona Komenda": "Gewerbegebiet Kirchheim",
    "PSE Lidl Domžale": "PV-Anlage Lidl Erding",
    "Poslovni park Ljubljana Vzhod": "Gewerbepark München Ost",
  };
  for (const row of book ?? []) {
    const name = BOOK[row.name];
    if (name) await db.from("projects").update({ name, country: "de", language: "de" }).eq("id", row.id);
    else await db.from("projects").update({ country: "de", language: "de" }).eq("id", row.id);
  }

  // 5. Every free-text string the mapping knows.
  let total = 0;
  for (const [table, columns] of CONTENT) {
    const changed = await translateTable(table, columns);
    if (changed) console.log(`  ${table.padEnd(22)} ${changed} value(s)`);
    total += changed;
  }

  console.log(`\ndemo dressed in German: ${total} content value(s) rewritten.`);
  console.log("Run `npm run seed` afterwards to restore the Slovenian demo.");
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
